In [1]:
import pandas as pd
import numpy as np

In [2]:
titanic_df = pd.read_csv('C:/Users/Lenovo/Desktop/Python/Pandas/Group By/Titanic_dataset.csv')

In [3]:
titanic_df.sample(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S
177,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C

**Q-1: Using groupby make groups using the "Pclass" column and find out the average age and total number of missing values in the "Age" column for every group.**

In [4]:
pclass = titanic_df.groupby('Pclass')

In [5]:
for group in list(pclass.groups.keys()):
    print("Group : {} , average_age : {} , total_nan_values : {}".format(group , pclass.get_group(group)['Age'].mean() ,pclass.get_group(group)['Age'].isna().sum()))

Group : 1 , average_age : 38.233440860215055 , total_nan_values : 30
Group : 2 , average_age : 29.87763005780347 , total_nan_values : 11
Group : 3 , average_age : 25.14061971830986 , total_nan_values : 136

In [6]:
for group,df in pclass:
    print("Group : {} , Avg_age : {} , total_nan_values : {}".format(group , df.Age.mean() , df.Age.isna().sum()))

Group : 1 , Avg_age : 38.233440860215055 , total_nan_values : 30
Group : 2 , Avg_age : 29.87763005780347 , total_nan_values : 11
Group : 3 , Avg_age : 25.14061971830986 , total_nan_values : 136

**Q-2: Using groupby make groups using the "Pclass" column and fill every group's "Embarked" column's missing values with the mode value of that group. After that, print every group's "Embarked" column's value counts in ascending order.**

In [7]:
def embarked(group):
    ser = group.Embarked.fillna(group.Embarked.mode())
    print(ser.sort_values())

In [8]:
for group,df in pclass:
    print(df.Embarked.fillna(df.Embarked.mode()))

1      C
3      S
6      S
11     S
23     S
      ..
871    S
872    S
879    C
887    S
889    C
Name: Embarked, Length: 216, dtype: str
9      C
15     S
17     S
20     S
21     S
      ..
866    C
874    C
880    S
883    S
886    S
Name: Embarked, Length: 184, dtype: str
0      S
2      S
4      S
5      Q
7      S
      ..
882    S
884    S
885    Q
888    S
890    Q
Name: Embarked, Length: 491, dtype: str

In [9]:
# if you want original changes Transform is tha best option as it return same column or row indices to be saved in original data frame
titanic_df.Embarked = titanic_df.groupby('Pclass')['Embarked'].transform(lambda x : x.fillna(x.mode()[0]))

In [10]:
titanic_df.Embarked.hasnans

False

In [11]:
titanic_df.groupby('Pclass').Embarked.value_counts(ascending=True)

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

**Q-3: Make groups based on "Embarked" column. And for each of this embarked group, make another group based on "Pclass" and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".**

In [12]:
dict(titanic_df.groupby(['Embarked' , 'Pclass']).Fare.mean().round(2))

{('C', 1): np.float64(104.72),
 ('C', 2): np.float64(25.36),
 ('C', 3): np.float64(11.21),
 ('Q', 1): np.float64(90.0),
 ('Q', 2): np.float64(12.35),
 ('Q', 3): np.float64(11.18),
 ('S', 1): np.float64(70.51),
 ('S', 2): np.float64(20.33),
 ('S', 3): np.float64(14.64)}

**But required output is : **
**Sample Output:**

{'C': {1: 105, 2: 25, 3: 11},

 'Q': {1: 90, 2: 12, 3: 11},

 'S': {1: 70, 2: 20, 3: 15}}

In [13]:
test= {}
test['A'] = {}
test['B'] = {}
test['C'] = {}
test['A'][1] = 'hi'
test['A'][2] = 'how'
test

{'A': {1: 'hi', 2: 'how'}, 'B': {}, 'C': {}}

In [14]:
# SOLUTION 
ans = {}
embarked_G = titanic_df.groupby('Embarked')
for group in embarked_G.groups.keys():
    ans[group] = {}
    pclass_G = embarked_G.get_group(group).groupby('Pclass')
    for p_group in pclass_G.groups.keys():
        ans[group][p_group] = round(float(pclass_G.get_group(p_group).Fare.mean()) , 2)

In [15]:
ans

{'C': {1: 104.72, 2: 25.36, 3: 11.21},
 'Q': {1: 90.0, 2: 12.35, 3: 11.18},
 'S': {1: 70.51, 2: 20.33, 3: 14.64}}

**Fifa_World_Cup DataSet**

In [16]:
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")

In [17]:
fifa_df.sample(3)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
107,108,54,Korea Republic,Brazil,H,1,44,0,1,0,...,13,5,548,486,14,1,4,8,0,0
76,77,39,Poland,Argentina,C,0,24,0,0,0,...,6,0,321,261,5,2,1,12,0,0
48,49,25,Japan,Costa Rica,E,0,47,0,0,0,...,22,0,591,522,15,1,5,11,0,0

In [18]:
fifa_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Sl. No                           128 non-null    int64
 1   Match No.                        128 non-null    int64
 2   Team                             128 non-null    str
 3   Against                          128 non-null    str
 4   Group                            128 non-null    str
 5   Goal                             128 non-null    int64
 6   Possession (%)                   128 non-null    int64
 7   Inside Penalty Area              128 non-null    int64
 8   Outside Penalty Area             128 non-null    int64
 9   Assists                          128 non-null    int64
 10  Total Attempts                   128 non-null    int64
 11  On Target                        128 non-null    int64
 12  Off Target                       128 non-null    int64
 13  Target in Penalty                128 non-null    int64
 14  Target from Outside              128 non-null    int64
 15  Left Channel                     128 non-null    int64
 16  Left Inside Channel              128 non-null    int64
 17  Central Channel                  128 non-null    int64
 18  Right Inside Channel             128 non-null    int64
 19  Right Channel                    128 non-null    int64
 20  Receptions MD                    128 non-null    int64
 21  Receptions D                     128 non-null    int64
 22  Attempted Line Breaks            128 non-null    int64
 23  Completed Line Breaks            128 non-null    int64
 24  Attempted Defensive Line Breaks  128 non-null    int64
 25  Completed Defensive Line Breaks  128 non-null    int64
 26  Yellow Cards                     128 non-null    int64
 27  Red Cards                        128 non-null    int64
 28  Fouls Against                    128 non-null    int64
 29  Offsides                         128 non-null    int64
 30  Passes                           128 non-null    int64
 31  Passes Completed                 128 non-null    int64
 32  Crosses                          128 non-null    int64
 33  Crosses Completed                128 non-null    int64
 34  Corners                          128 non-null    int64
 35  Free Kicks                       128 non-null    int64
 36  Penalties Scored                 128 non-null    int64
 37  Pts                              128 non-null    int64
dtypes: int64(35), str(3)
memory usage: 38.1 KB

In [19]:
fifa_df.shape

(128, 38)

**-4: Perform groupby based on the "Team" column and then perform Z Normalization on top of the below columns of each group:**
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks
**You have to make a python function named z_normalization which takes two arguments:**

1. group: Every group that you have created
2. cols_to_perform: This parameter takes a list of columns on which you have to perform the Z-Normalization.
**For this problem, you have to use th apply() method.**

**Z − Normalization=Xi−μstd**

After that find out the below values for each group:

1. minimum "Passess"
2. maximum "Passess"
3. minimum "Yellow Cards"
4. maximum "Yellow cards"
5. average "Yellow Cards"
6. maximum "Attempted Line Breaks"
7. minimum "Attempted Line Breaks"
8. standardard deviation of "Attempted Line Breaks"
9. average Possession

In [20]:
team_Gr =fifa_df.groupby('Team')
def z_normalization(group , columns):
    for col in columns:
        group['z_norm'] = (group[col] - group[col].mean()) / group[col].std()
    return group

In [21]:
new_df = team_Gr.apply(z_normalization , columns= ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"])

In [22]:
team_Gr  = new_df.groupby('Team')

In [23]:
team_Gr.agg({
           'Passes' : ['min' , 'max'] ,
           'Yellow Cards' : ['max' , 'mean'] ,
            'Attempted Line Breaks' : ['max' , 'min' , 'std'] ,
            'Possession (%)' : 'mean'

})

               Passes       Yellow Cards           Attempted Line Breaks       \
                  min   max          max      mean                   max  min
Team
Argentina         408   862            8  2.285714                   249  141
Australia         286   466            3  1.750000                   171  133
Belgium           512   685            3  1.666667                   195  167
Brazil            548   695            3  1.200000                   193  164
Cameroon          295   500            5  2.666667                   182  144
Canada            448   536            4  2.666667                   176  102
Costa Rica        231   454            3  2.000000                   154   86
Croatia           461   724            2  1.142857                   259   97
Denmark           537   650            2  1.666667                   241  173
Ecuador           429   484            2  1.000000                   177  143
England           508   810            1  0.200000                   208  133
France            358   734            3  1.142857                   179  126
Germany           352   827            3  1.000000                   256  143
Ghana             319   460            4  2.666667                   188  122
Iran              232   463            3  2.333333                   195   56
Japan             225   591            3  1.500000                   253  104
Korea Republic    359   548            2  1.500000                   201  139
Mexico            356   500            4  2.333333                   198  127
Morocco           229   583            3  1.285714                   157  128
Netherlands       403   786            4  1.800000                   198  168
Poland            303   466            3  1.750000                   156   79
Portugal          461   678            3  1.200000                   197  165
Qatar             424   457            4  2.333333                   174  159
Saudi Arabia      267   560            6  4.666667                   205  147
Senegal           277   511            3  1.750000                   184  143
Serbia            403   513            7  4.000000                   184  140
Spain             647  1070            1  0.500000                   237  186
Switzerland       403   512            4  2.250000                   178  157
Tunisia           328   501            3  1.666667                   200  153
United States     427   572            4  1.250000                   204  143
Uruguay           390   528            3  2.000000                   186  146
Wales             325   508            2  1.666667                   208  104

                          Possession (%)
                      std           mean
Team
Argentina       38.774685      49.285714
Australia       17.682383      31.250000
Belgium         14.422205      49.000000
Brazil          10.691118      50.400000
Cameroon        19.857828      38.333333
Canada          37.753587      44.333333
Costa Rica      38.974351      27.333333
Croatia         54.499891      47.428571
Denmark         34.000000      51.333333
Ecuador         17.009801      42.666667
England         29.676590      57.200000
France          21.407609      44.857143
Germany         56.624494      53.000000
Ghana           33.020196      37.000000
Iran            77.526340      31.666667
Japan           64.048810      30.250000
Korea Republic  27.072434      42.250000
Mexico          40.706265      46.666667
Morocco         10.641339      34.285714
Netherlands     12.759310      44.000000
Poland          36.326070      32.000000
Portugal        13.049904      53.800000
Qatar            7.767453      39.333333
Saudi Arabia    29.022979      36.666667
Senegal         16.938615      38.500000
Serbia          22.188586      42.666667
Spain           24.289916      67.000000
Switzerland      9.032349      43.000000
Tunisia         24.419937      38.666667
United States   27.693260      47.000000
Uruguay         22.030282      41.000000
Wales           53.028294      41.000000

In [24]:
fifa_df.columns

Index(['Sl. No', 'Match No.', 'Team', 'Against', 'Group', 'Goal',
       'Possession (%)', 'Inside Penalty Area', 'Outside Penalty Area',
       'Assists', 'Total Attempts', 'On Target', 'Off Target',
       'Target in Penalty', 'Target from Outside', 'Left Channel',
       'Left Inside Channel', 'Central Channel', 'Right Inside Channel',
       'Right Channel', 'Receptions MD', 'Receptions D',
       'Attempted Line Breaks', 'Completed Line Breaks',
       'Attempted Defensive Line Breaks', 'Completed Defensive Line Breaks',
       'Yellow Cards', 'Red Cards', 'Fouls Against', 'Offsides', 'Passes',
       'Passes Completed', 'Crosses', 'Crosses Completed', 'Corners',
       'Free Kicks', 'Penalties Scored', 'Pts'],
      dtype='str')

**Questions on IPL**

In [52]:
ipl = pd.read_csv('C:/Users/Lenovo/Desktop/Python/Pandas/Group By/ipl_deliveries.csv')

**Q-5: Find batsman in below category-**

1. Highest score while chasing
2. Best Strike rate while chasing and have faced 100+ balls
3. Chasing mean team batting in second inning

In [26]:
ipl.sample(2)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
57924,1175369,Royal Challengers BangaloreRajasthan Royals,2,3,6,JC Buttler,Navdeep Saini,AM Rahane,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Royal Challengers Bangalore
52970,1178409,Mumbai IndiansDelhi Capitals,1,1,1,RG Sharma,K Rabada,Q de Kock,NaN,1,0,1,0,0,NaN,NaN,NaN,Mumbai Indians,Delhi Capitals

In [27]:
sec_ininigs = ipl[ipl.innings == 2]

In [28]:
batsman_group = sec_ininigs.groupby('batter').filter(lambda x : x['ballnumber'].count() >= 100)

In [29]:

batsman_group = batsman_group.groupby('batter')

In [30]:
# strike rates of batsmen while facing more than 100 balls 
strike_rate = batsman_group.apply(lambda x : (x['batsman_run'].sum()/x['ballnumber'].count())*100   )
strike_rate

batter
A Mishra            92.735043
A Symonds          113.915858
AB de Villiers     134.885290
AC Gilchrist       142.171717
AD Mathews         114.598540
                      ...
Y Venugopal Rao    119.280206
YBK Jaiswal        140.760870
YK Pathan          145.320959
YV Takawale        106.557377
Yuvraj Singh       115.456238
Length: 185, dtype: float64

In [31]:
batsman_group.batter.nunique()

batter
A Mishra           1
A Symonds          1
AB de Villiers     1
AC Gilchrist       1
AD Mathews         1
                  ..
Y Venugopal Rao    1
YBK Jaiswal        1
YK Pathan          1
YV Takawale        1
Yuvraj Singh       1
Name: batter, Length: 185, dtype: int64

In [32]:
high_chasers = sec_ininigs.groupby('batter').batsman_run.sum().sort_values(ascending=False)
high_chasers

batter
V Kohli         3070
DA Warner       2839
RV Uthappa      2832
S Dhawan        2707
RG Sharma       2464
                ...
Abdur Razzak       0
AN Ghosh           0
Akash Deep         0
VRV Singh          0
AS Roy             0
Name: batsman_run, Length: 552, dtype: int64

In [33]:
strike_rate = strike_rate.reset_index().rename(columns={0 : 'Strike_rate'})

In [34]:
high_chasers = high_chasers.reset_index().rename(columns={'batsman_run' : 'runs_while_chasing'})

In [35]:
high_chasers.merge(strike_rate , on= 'batter').sort_values(by= [  'runs_while_chasing' ,'Strike_rate']  , ascending=False)

         batter  runs_while_chasing  Strike_rate
0       V Kohli                3070   127.174814
1     DA Warner                2839   138.352827
2    RV Uthappa                2832   130.326737
3      S Dhawan                2707   123.157416
4     RG Sharma                2464   119.844358
..          ...                 ...          ...
180    K Rabada                 107    99.074074
181     MS Wade                 102   102.000000
182      K Goel                  97    79.508197
183     PK Garg                  96    94.117647
184    R Dhawan                  92    90.196078

[185 rows x 3 columns]

**Q-6 Most Successful bowler against any batsman. Find that pair of bowler and batsman.**

**Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.**

In [36]:
ipl.sample(3)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
223763,335991,Kings XI PunjabMumbai Indians,2,9,5,SS Tiwary,VRV Singh,SM Pollock,NaN,0,0,0,0,0,NaN,NaN,NaN,Mumbai Indians,Kings XI Punjab
213851,336037,Deccan ChargersChennai Super Kings,2,17,1,SK Raina,PP Ojha,JA Morkel,NaN,2,0,2,0,0,NaN,NaN,NaN,Chennai Super Kings,Deccan Chargers
118331,734039,Kings XI PunjabDelhi Daredevils,1,4,4,KD Karthik,MG Johnson,KP Pietersen,NaN,1,0,1,0,0,NaN,NaN,NaN,Delhi Daredevils,Kings XI Punjab

In [37]:
ipl['Is_Out'] = ipl.batter == ipl.player_out

In [38]:
df = ipl.groupby(['bowler' , 'batter'])

In [39]:
df.agg({
        'Is_Out' : 'sum' ,
         'batsman_run' : 'sum'
}).sort_values(by=['Is_Out' , 'batsman_run'] , ascending=[False , True]).head()

                           Is_Out  batsman_run
bowler         batter
Z Khan         MS Dhoni         7           74
Sandeep Sharma V Kohli          7           78
A Mishra       RG Sharma        7           87
R Ashwin       RV Uthappa       7          123
SP Narine      RG Sharma        7          137

**Q-7: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.**

In [53]:
ipl['pair'] = ipl.apply(lambda x : '-'.join(sorted([x['batter'] , x['non-striker']])) , axis=1)

In [54]:
ipl.sample(3)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,pair
222252,335997,Kolkata Knight RidersMumbai Indians,1,12,5,Mohammad Hafeez,SM Pollock,RT Ponting,NaN,1,0,1,0,0,NaN,NaN,NaN,Kolkata Knight Riders,Mumbai Indians,Mohammad Hafeez-RT Ponting
66920,1136597,Mumbai IndiansKolkata Knight Riders,2,13,4,KD Karthik,HH Pandya,AD Russell,NaN,1,0,1,0,0,NaN,NaN,NaN,Kolkata Knight Riders,Mumbai Indians,AD Russell-KD Karthik
83305,1082616,Gujarat LionsKings XI Punjab,2,13,4,KD Karthik,KC Cariappa,AJ Tye,NaN,1,0,1,0,0,NaN,NaN,NaN,Gujarat Lions,Kings XI Punjab,AJ Tye-KD Karthik

In [56]:
ipl.groupby('pair').batsman_run.sum().sort_values(ascending=False)

pair
AB de Villiers-V Kohli       3040
CH Gayle-V Kohli             2650
DA Warner-S Dhawan           2242
G Gambhir-RV Uthappa         1795
KL Rahul-MA Agarwal          1664
                             ...
Ankit Sharma-DB Ravi Teja       0
Anirudh Singh-MD Mishra         0
Akash Deep-KD Karthik           0
RP Singh-S Sreesanth            0
RP Singh-RV Gomez               0
Name: batsman_run, Length: 4259, dtype: int64

**Q-8: Make a dataframe for all batting pairs played together.

Batsman1 | Batsman2 | Runs | Avg | StrikeRate

Just to ease this question you can count wide-balls for strike rate.**

In [60]:
temp_df = ipl.groupby('pair').agg({
      'batsman_run' : 'sum' ,
      'isWicketDelivery' : 'sum',
       'ballnumber' : 'count'
})

In [62]:
temp_df['Avergae'] = temp_df['batsman_run'] / temp_df['isWicketDelivery']

In [64]:
temp_df['Strike_rate']= (temp_df['batsman_run'] / temp_df['ballnumber']) * 100

In [67]:
temp_df.drop(columns=['isWicketDelivery' ,'ballnumber' ] , inplace=True)

In [74]:
temp_df.reset_index(inplace=True)

In [75]:
temp_df['Batsman1'] = temp_df.apply(lambda row : row['pair'].split('-')[0]  , axis=1)

In [77]:
temp_df['Batsman2'] = temp_df['pair'].apply(lambda row : row.split('-')[1])

In [83]:
temp_df.rename(columns={'batsman_run' : 'Runs'} , inplace=True)

In [88]:
temp_df[['Batsman1' , 'Batsman2' ,'Runs' , 'Avergae' , 'Strike_rate']].sort_values('Runs'  , ascending=False)

            Batsman1      Batsman2  Runs    Avergae  Strike_rate
302   AB de Villiers       V Kohli  3040  42.816901   147.644488
1251        CH Gayle       V Kohli  2650  50.000000   134.313229
1508       DA Warner      S Dhawan  2242  45.755102   129.971014
1954       G Gambhir    RV Uthappa  1795  37.395833   125.964912
2803        KL Rahul    MA Agarwal  1664  50.424242   137.407102
...              ...           ...   ...        ...          ...
835     Ankit Sharma  DB Ravi Teja     0   0.000000     0.000000
828    Anirudh Singh     MD Mishra     0   0.000000     0.000000
826       Akash Deep    KD Karthik     0   0.000000     0.000000
3933        RP Singh   S Sreesanth     0   0.000000     0.000000
3932        RP Singh      RV Gomez     0        NaN     0.000000

[4259 rows x 5 columns]